import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { GeneratorOutput, ReviewerOutput, Mcq, MCQOption } from '@workspace/api-client-react';
import { CheckCircle2, XCircle, BrainCircuit, PenTool, CheckSquare } from 'lucide-react';
import { cn } from '@/lib/utils';

export function GeneratorStage({
  data,
  isLoading,
  title = "Generator Output",
  description = "Initial content generated by the AI teacher",
}: {
  data?: GeneratorOutput | null;
  isLoading?: boolean;
  title?: string;
  description?: string;
}) {
  if (isLoading) {
    return (
      <Card className="border-border bg-card/50 shadow-sm opacity-80 animate-pulse">
        <CardHeader>
          <div className="flex items-center gap-3">
            <BrainCircuit className="h-5 w-5 text-muted-foreground" />
            <div>
              <CardTitle className="text-lg">Generating Content...</CardTitle>
              <CardDescription>Synthesizing grade-appropriate material</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-[90%]" />
          <Skeleton className="h-4 w-[95%]" />
          <Skeleton className="h-4 w-[80%]" />
          <div className="pt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <Skeleton className="h-32 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!data) return null;

  return (
    <Card className="animate-in-slide-up overflow-hidden border-border shadow-sm">
      <CardHeader className="bg-muted/20 border-b border-border/50 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-primary/10 text-primary">
            <BrainCircuit className="h-5 w-5" />
          </div>
          <div>
            <CardTitle className="text-lg">{title}</CardTitle>
            <CardDescription>{description}</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 space-y-6">
        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">Explanation</h4>
          <div className="prose prose-sm dark:prose-invert max-w-none text-foreground font-serif leading-relaxed">
            {data.explanation.split('\n').map((paragraph: string, idx: number) => (
              paragraph.trim() ? <p key={idx} className="mb-4 last:mb-0">{paragraph}</p> : null
            ))}
          </div>
        </div>

        <div>
          <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">Multiple Choice Questions</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {data.mcqs.map((mcq: Mcq, idx: number) => (
              <div key={idx} className="border border-border rounded-lg p-4 bg-muted/10">
                <p className="text-sm font-medium mb-3">{mcq.question}</p>
                <div className="space-y-2">
                  {mcq.options.map((opt: MCQOption) => {
                    const isCorrect = opt.label === mcq.answer;
                    return (
                      <div 
                        key={opt.label}
                        className={cn(
                          "flex items-start gap-2 text-sm p-2 rounded-md transition-colors",
                          isCorrect ? "bg-[hsl(var(--success))]/10 text-[hsl(var(--success))]" : "bg-background border border-border"
                        )}
                      >
                        <span className="font-semibold text-xs mt-0.5">{opt.label}.</span>
                        <span>{opt.text}</span>
                        {isCorrect && <CheckCircle2 className="h-4 w-4 ml-auto shrink-0 mt-0.5" />}
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export function ReviewerStage({
  data,
  isLoading
}: {
  data?: ReviewerOutput | null;
  isLoading?: boolean;
}) {
  if (isLoading) {
    return (
      <Card className="border-border bg-card/50 shadow-sm opacity-80 animate-pulse mt-6">
        <CardHeader>
          <div className="flex items-center gap-3">
            <CheckSquare className="h-5 w-5 text-muted-foreground" />
            <div>
              <CardTitle className="text-lg">Reviewing Content...</CardTitle>
              <CardDescription>Validating against curriculum standards</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          <Skeleton className="h-8 w-24 mb-4" />
          <Skeleton className="h-4 w-[70%]" />
          <Skeleton className="h-4 w-[85%]" />
        </CardContent>
      </Card>
    );
  }

  if (!data) return null;

  const passed = data.status === 'pass';

  return (
    <Card className="animate-in-slide-up mt-6 border-border shadow-sm overflow-hidden" style={{ animationDelay: '100ms' }}>
      <CardHeader className="bg-muted/20 border-b border-border/50 pb-4">
        <div className="flex justify-between items-start">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-secondary text-secondary-foreground">
              <CheckSquare className="h-5 w-5" />
            </div>
            <div>
              <CardTitle className="text-lg">Reviewer Feedback</CardTitle>
              <CardDescription>Quality assurance check</CardDescription>
            </div>
          </div>
          <Badge variant={passed ? "success" : "fail"} className="text-sm px-3 py-1 flex items-center gap-1.5">
            {passed ? <CheckCircle2 className="h-4 w-4" /> : <XCircle className="h-4 w-4" />}
            {passed ? "Approved" : "Needs Refinement"}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="p-6">
        {data.feedback.length === 0 ? (
          <p className="text-sm text-muted-foreground italic">
            {passed
              ? "Content approved — no issues found."
              : "No specific feedback provided."}
          </p>
        ) : (
          <ul className="space-y-3">
            {data.feedback.map((item: string, idx: number) => (
              <li key={idx} className="flex gap-3 text-sm items-start">
                <div className={cn(
                  "w-1.5 h-1.5 rounded-full mt-1.5 shrink-0",
                  passed ? "bg-[hsl(var(--success))]" : "bg-[hsl(var(--fail))]"
                )} />
                <span className={cn(
                  "leading-relaxed",
                  passed ? "text-muted-foreground" : "text-foreground font-medium"
                )}>{item}</span>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

export function RefinedStage({
  data,
}: {
  data?: GeneratorOutput | null;
}) {
  if (!data) return null;

  return (
    <div className="mt-6 pt-6 border-t-2 border-dashed border-border relative">
      <div className="absolute left-1/2 -top-3 -translate-x-1/2 bg-background px-4 text-xs font-bold uppercase tracking-widest text-muted-foreground">
        Pipeline Auto-Correction
      </div>
      <GeneratorStage 
        data={data} 
        title="Refined Output" 
        description="Content improved based on reviewer feedback"
      />
    </div>
  );
}
